---
title: "W4: tidy_up_stock_data"
execute:
  keep-md: true
  df-print: paged
  warning: false
  echo: false
format:
  html:
    code-fold: true
    code-line-numbers: true
    fig-width: 10
date: "`r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---

```{r}
library(readr)
library(tidyverse)
library(dplyr)
library(pander)
```
```{r}
rds_dat <- read_rds("https://github.com/byuistats/data/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.RDS")
```
```{r}
view(rds_dat)
```
```{r}
#data1<- data %>%
 # separate(contest_period, into = c("start_month", "end_month"), sep = "-")
sep_rds<- rds_dat %>%
  separate(contest_period, into = c("start_month", "end_month"), sep = "-") %>%
  mutate(end_year = substr(end_month, nchar(end_month)-4+1,nchar(end_month))) %>%
  mutate(start_month = substr(start_month,1,3)) %>%
  mutate(end_month = substr(end_month,1,3))
```

```{r}
data1 <- rds_dat %>%
  separate(contest_period, into = c("start_month", "end_month"), sep = "-") %>%
  separate(end_month, into = c("Month", "end_year"), sep = -4)
```
```{r}
month<- data1 %>%
    mutate(Month = replace(Month, Month == "Dec.","December")) %>%
  mutate(Month = replace(Month, Month == "Febuary","February"))
```

```{r}
new <- month %>%
    select(Month, end_year, variable, value) %>%
    pivot_wider(names_from = end_year, values_from = value) %>%
    filter(variable =="DJIA")%>%
    arrange(match(Month, month.name))
```
```{r}
panderOptions("missing", "-")
pander(new)
```

