---
title: "W3: Our world data 1"
execute:
  keep-md: true
  df-print: paged
  warning: false
  echo: false
format:
  html:
    code-fold: true
    code-line-numbers: true
    fig-width: 10
date: "`r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
library(dplyr)
library(ggrepel)
library(directlabels)
library(scales)
```

```{r}
dat <-fruit_consumption_vs_gdp_per_capita%>%fill(Continent, Entity)%>%
    rename("gdp_cap" = "GDP per capita, PPP (constant 2017 international $)", "fruit_person" = "Fruit | 00002919 || Food available for consumption | 0645pc || kilograms per year per capita")%>%filter(Year == '2020')%>%
  mutate(gdp_cap = round(gdp_cap, 2),
       fruit_person = round(fruit_person, 2),
       fruit_person =  ifelse(is.na(fruit_person), 0, fruit_person),
        gdp_cap = ifelse(is.na(gdp_cap), 0,gdp_cap))
View(dat)
```

```{r}
ggplot(dat , aes(x = gdp_cap,
                        y = fruit_person,
                        label = Entity
                           ))+
geom_point(aes(color = Continent))+
labs(x = "GDP per capita",
    y = "Fruit supply per person",
    title = "Fruit consumption vs. GDP per capita, 2020"
                        )+
theme( plot.title = element_text(hjust = 0.5),
    axis.line.y  = element_blank(),
    axis.line.x.bottom = element_line(),
    panel.grid.major = element_line(linetype = "dashed", color = "gray"),
    panel.grid.minor = element_line(linetype = "dashed", color = "gray"),
    panel.background = element_rect(fill = "white"))+
geom_text_repel(aes(label = Entity))+
scale_x_continuous(trans = 'log', breaks = c(1000, 2000, 5000, 10000, 20000, 100000), labels = c("$1,000", "$2,000", "$5,000", '$10,000', '$20,000', '$10,0000'))+
scale_y_continuous(breaks =seq(0, 350, by= 50), labels = unit_format(unit = 'kg'))


```

```{r}
dat_countries<- dat %>% filter(Entity %in% c("Hong Kong", "Iceland", "India"))
```
```{r}
ggplot(dat_countries, aes(x = gdp_cap, y = fruit_person, color = Entity)) +
    geom_point(data = dat %>% filter(!(Entity %in% c("Hong Kong", "Iceland", "India"))), aes(x = gdp_cap, y = fruit_person), color = "grey50", alpha = 0.3) +
geom_point() + # the countries geom_point is written last in order to have a higher z priority
  geom_text_repel(data = dat_countries, aes(label = Entity)) +
  labs(title = "Fruit consumption vs. GDP per capita", x = "GDP per capita", y = "Fruit supply per person") +
  guides(color = guide_legend(title = "Countries")) +
  theme_bw()
```

```{r}
dat %>% filter(Continent == "Europe") %>% 
  ggplot(aes(x = gdp_cap,
             y = fruit_person,
              label = Entity
                           ))+
geom_point(aes(color = Continent))+
labs(x = "GDP per capita",
    y = "Fruit supply per person",
    title = "Fruit consumption vs. GDP per capita, 2020"
                        )+
theme( plot.title = element_text(hjust = 0.5),
    axis.line.y  = element_blank(),
    axis.line.x.bottom = element_line(),
    panel.grid.major = element_line(linetype = "dashed", color = "gray"),
    panel.grid.minor = element_line(linetype = "dashed", color = "gray"),
    panel.background = element_rect(fill = "white"))+
geom_text_repel(aes(label = Entity))+
scale_x_continuous(trans = 'log', breaks = c(1000, 2000, 5000, 10000, 20000, 100000), labels = c("$1,000", "$2,000", "$5,000", '$10,000', '$20,000', '$10,0000'))+
scale_y_continuous(breaks =seq(0, 350, by= 50), labels = unit_format(unit = 'kg'))
```

## Summary
Creating these graphs has been a valuable learning experience for me, especially when it comes to effectively segregating data and crafting visualizations that incorporate multiple datasets.