---
title: "W8: USA_cities"
execute:
  keep-md: true
  df-print: paged
  warning: false
  echo: false
format:
  html:
    code-fold: true
    code-line-numbers: true
    fig-width: 10
date: "`r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---

```{r}
library(USAboundaries)
library(USAboundariesData)
library(tidyverse)
library(sf)
library(ggrepel)
library(mosaic)
```

```{r}
states <- us_states()
idaho_counties <- us_counties(state="Idaho")

states48 <- us_states() %>% filter(stusps != "AK" & stusps != "HI" & stusps != "PR")

cities48 <- us_cities() %>% filter(state_abbr != "AK" & state_abbr != "HI" & state_abbr != "PR")
```

```{r}
top_three_c <- cities48 %>%
  arrange(desc(population)) %>% 
  group_by(state_name) %>%
  slice(1:3) %>% 
  mutate(
    rank = row_number(state_name)
  ) %>% 
  arrange(desc(rank))
```

```{r}
ggplot() +
  geom_sf(data=states48, fill="white", color = "black") +
  geom_sf(data=idaho_counties, fill="white", color = "black") +
  geom_sf(data=top_three_c, aes(color=rank, size=population/1000)) +
  geom_label_repel(data=top_three_c, aes(label=ifelse(rank==1, city, NA), geometry=geometry), stat="sf_coordinates", size=2, label.padding=.15, color="darkblue", max.overlaps = 2000) +
  labs(
    x="",
    y=""
  ) +
  theme_bw() +
  guides(
    colour = "none",
    size = guide_legend("Population\n(1,000)", override.aes = list(color="darkblue"))
  ) +
  theme_minimal()
```
